--  DRAFT TO DO : fix time valuesin select with strftime("HH:MM")
--  TO DO: CHECK THAT PRIMARY KEY WILL WORK WITH THESE DATA
-- to do : make list of all changed field names

-- tblDarting_fix.sql
-- post-processing of table darting after direct import from MS Access
-- sqlite format  
-- usage:  first create sqlite database from MS Access, 
-- then sqlite3 my_database.sqlite3 < this_file.sql


-- version 0.1 
--     change date/times formats to only dates or only times,
--     rename several columns that have inappropriate characters for database fiels

PRAGMA foreign_keys=OFF;

DROP TABLE IF EXISTS darting;

CREATE TABLE darting (
         hyena                       varchar,
         id                          varchar,
         kaycode                     integer,
         eartagnumber                integer,
         codenumberonsamples         varchar,
         dartingdate                 date,
         darter                      varchar,
         location                    varchar,
         gpsutme                     integer,
         gpsutmn                     integer,
         founddead                   integer,
         sex                         varchar,
         age                         varchar,
         agemonths                   real,
         ageclass                    integer,
         clan                        varchar,
         natalorimmigrant            varchar,
         reproductivestatus          varchar,
         reprostatcode               varchar,
         maternalrank                real,
         mass                        real,
         telazoldose                 real,
         telazolbooster              real,
         dartingtime                 time,
         timedown                    time,  --duration?
         bloodsamplingtime           time,  --duration?
         radiocollared               integer,
         radiofreq                   varchar,
         radioserialnum              varchar,
         gnrh                        integer,
         numedtawholeblood           varchar,
         numedtaplasma               varchar,
         numedtabuffycoat            varchar,
         numserum                    varchar,
         numrbc                      varchar,
         numheparinplasma            varchar,
         numurine                    varchar,
         numpaste                    varchar,
         numtissues                  varchar,
         dnaextracted                varchar,
         numthinbloodsmears          varchar,
         numthickbloodsmears         varchar,
         ultrasound                  integer,
         numfetuses                  integer,
         numheartbeats               integer,
         ultrasoundother             text,
         fetuslength_r-l             varchar,
         parasites                   varchar,
         parasite_ticks              integer,
         parasites_lionfiles         integer,
         parasites_other             integer,
         glucose_grn-red             varchar,
         glucosegreen                real,
         glucosered                  real,
         pcv                         real,
         wbc                         integer,
         rbc                         integer,
         knottsmicrofilaria          varchar,  
         totalsolids                 real,
         zygototopcrest              real,
         zygotobackcrest             real,
         eyetoear                    real,
         earlength                   real,
         skulllength                 real,
         headcirc                    real,
         zygobreadth                 real,
         bodylength                  real,
         taillength                  real,
         neckcirc                    real,
         girth                       real,
         legside                     varchar,
         frontftlen                  real,
         lowerleglength              real,
         upperleglength              real,
         scapulalength               real,
         htatshoulder                real,
         hindftlength                real,
         test-niplength              varchar,
         test-nipwidth               varchar,
         toothside                   varchar,
         incisors                    real,
         upcanineht                  real,
         uppm2len                    real,
         uppm3len                    real,
         uppm4len                    real,
         upperrowlen                 real,
         lowerrowlen                 real,
         lowrowwithm1len             real,
         m1length                    real,
         lowpm4len                   real,
         lowpm3len                   real,
         lowpm2len                   real,
         lowcanineht                 real,
         rtlowpm3ht                  real,
         lftlowpm3ht                 real,
         rtlowpm3surf                real,
         lftlowpm3surf               real,
         cavities-broken teeth       text,
         kidteeth                    text,
         bodycondition               varchar,
         scars-wounds                text,
         dartsheetcomments           text,
         reactionto darting          text,
         notes                       text,
         numwbc                      varchar,
         numrtbuffer                 varchar,
         othercollected              varchar,
         temperature                 varchar,
         respiration                 varchar,
         heartrate                   varchar,
         bodyfat                     text,
         old_codenumber              integer,
         old_2ndnumber               integer,
         estimatedagemo              varchar,
         ageatdartingdays            real,
         ageatdartingnote            varchar,   
         PRIMARY KEY(hyena,dartingdate)
);

CREATE INDEX dartingdate_index ON sessions ("dartingdate");
-- add more indexes and foreign keys here

INSERT INTO darting (   hyena,
  id,
  kaycode,
  eartagnumber,
  codenumberonsamples,
  dartingdate,
  darter,
  location,
  gpsutme,
  gpsutmn,
  founddead,
  sex,
  age,
  agemonths,
  ageclass,
  clan,
  natalorimmigrant,
  reproductivestatus,
  reprostatcode,
  maternalrank,
  mass,
  telazoldose,
  telazolbooster,
  dartingtime,
  timedown,
  bloodsamplingtime,
  radiocollared,
  radiofreq,
  radioserialnum,
  gnrh,
  numedtawholeblood,
  numedtaplasma,
  numedtabuffycoat,
  numserum,
  numrbc,
  numheparinplasma,
  numurine,
  numpaste,
  numtissues,
  dnaextracted,
  numthinbloodsmears,
  numthickbloodsmears,
  ultrasound,
  numfetuses,
  numheartbeats,
  ultrasoundother,
  fetuslength_r-l,
  parasites,
  parasite_ticks,
  parasites_lionfiles,
  parasites_other,
  glucose_grn-red,
  glucosegreen,
  glucosered,
  pcv,
  wbc,
  rbc,
  knottsmicrofilaria,
  totalsolids,
  zygototopcrest,
  zygotobackcrest,
  eyetoear,
  earlength,
  skulllength,
  headcirc,
  zygobreadth,
  bodylength,
  taillength,
  neckcirc,
  girth,
  legside,
  frontftlen,
  lowerleglength,
  upperleglength,
  scapulalength,
  htatshoulder,
  hindftlength,
  test-niplength,
  test-nipwidth,
  toothside,
  incisors,
  upcanineht,
  uppm2len,
  uppm3len,
  uppm4len,
  upperrowlen,
  lowerrowlen,
  lowrowwithm1len,
  m1length,
  lowpm4len,
  lowpm3len,
  lowpm2len,
  lowcanineht,
  rtlowpm3ht,
  lftlowpm3ht,
  rtlowpm3surf,
  lftlowpm3surf,
  cavities-broken teeth,
  kidteeth,
  bodycondition,
  scars-wounds,
  dartsheetcomments,
  reactionto darting,
  notes,
  numwbc,
  numrtbuffer,
  othercollected,
  temperature,
  respiration,
  heartrate,
  bodyfat,
  old_codenumber,
  old_2ndnumber,
  estimatedagemo,
  ageatdartingdays,
  ageatdartingnote)
  
SELECT 
        `Hyena` as hyena,
        `ID`,
        `KayCode`,
        `EarTagNumber`,
        `CodeNumberOnSamples`,
        strftime('%Y-%m-%d',`DartingDate`) as dartingdate,
        `Darter`,
        `Location`,
        `GPSUTMe`,
        `GPSUTMn`,
        `FoundDead`,
        `Sex`,
        `Age`,
        `AgeMonths`,
        `AgeClass`,
        `Clan`,
        `NatalOrImmigrant`,
        `ReproductiveStatus`,
        `ReproStatCode`,
        `MaternalRank`,
        `Mass`,
        `TelazolDose`,
        `TelazolBooster`,
        `DartingTime`,
        `TimeDown`,
        `BloodSamplingTime`,
        `RadioCollared`,
        `RadioFreq`,
        `RadioSerialNum`,
        `GnRH`,
        `NumEDTAWholeBlood`,
        `NumEDTAPlasma`,
        `NumEDTABuffyCoat`,
        `NumSerum`,
        `NumRBC`,
        `NumHeparinPlasma`,
        `NumUrine`,
        `NumPaste`,
        `NumTissues`,
        `DNAExtracted`,
        `NumThinBloodSmears`,
        `NumThickBloodSmears`,
        `Ultrasound`,
        `NumFetuses`,
        `NumHeartbeats`,
        `UltrasoundOther`,
        `FetusLength(R/L)`,
        `Parasites`,
        `Parasite_ticks`,
        `Parasites_lionfiles`,
        `Parasites_other`,
        `GLUCOSE(grn/red)`,
        `GlucoseGreen`,
        `GlucoseRed`,
        `PCV`,
        `WBC`,
        `RBC`,
        `Knott'sMicrofilaria`,
        `TotalSolids`,
        `ZygoToTopCrest`,
        `ZygoToBackCrest`,
        `EyeToEar`,
        `EarLength`,
        `SkullLength`,
        `HeadCirc`,
        `ZygoBreadth`,
        `BodyLength`,
        `TailLength`,
        `NeckCirc`,
        `Girth`,
        `LegSide`,
        `FrontFtLen`,
        `LowerLegLength`,
        `UpperLegLength`,
        `ScapulaLength`,
        `HtAtShoulder`,
        `HindFtLength`,
        `Test/NipLength`,
        `Test/NipWidth`,
        `ToothSide`,
        `Incisors`,
        `UpCanineHt`,
        `UpPM2Len`,
        `UpPM3Len`,
        `UpPM4Len`,
        `UpperRowLen`,
        `LowerRowLen`,
        `LowRowWithM1Len`,
        `M1Length`,
        `LowPM4Len`,
        `LowPM3Len`,
        `LowPM2Len`,
        `LowCanineHt`,
        `RtLowPM3Ht`,
        `LftLowPM3Ht`,
        `RtLowPM3Surf`,
        `LftLowPM3Surf`,
        `Cavities/Broken Teeth`,
        `KidTeeth`,
        `BodyCondition`,
        `Scars/Wounds`,
        `DartsheetComments`,
        `ReactionTo Darting`,
        `Notes`,
        `NumWBC`,
        `NumRTBuffer`,
        `OtherCollected`,
        `Temperature`,
        `Respiration`,
        `HeartRate`,
        `BodyFat`,
        `old_CodeNumber`,
        `old_2ndNumber`,
        `EstimatedAgeMo`,
        `AgeAtDartingDays`,
        `AgeAtDartingNote`
        
from tblDarting
order by dartingdate,hyena;

PRAGMA foreign_keys=ON;

